## Архитектура сервера API
Сервер не имеет сложной логики и является оберткой над `CLI git` 

### Логические модули:
1. [Роутер](../server/routes/api.js) (обработка запроса по какому-либо маршруту)
2. [Модуль actions](../server/modules/actions.js) и его подмодули (вызов комманд `git`)
3. [Модуль utils](../server/modules/utils.js) (вспомогательные функции для этих двух модулей)

#### 1. Роутер
Отвечает за то, чтобы по некоторому маршруту апи был вызван правильное действие
из модуля `Actions`.

Основные сценарии:
1. Только вызывает модуль `Actions` и возвращает то, что получит в ответ (и данные, и ошибку)

Тестируется [тут](../test/unit/router/index.test.js)

#### 2. Actions
Отвечает за:
1. вызов правильной `git`-комманды
2. если комманда сработала успешно - возвращает данные,
если что-то пошло не так ошибку (которая является инстансом [Response](../server/models/responses/response.js))
3. троттлинг вызовов одинаковых `Actions`, если комманда выполняется, нет смысла выполнять ее несколько раз, правильно?
Особенно если это комманда `Вытянуть всю историю коммитов из ветки мастер`

Основные сценарии:
1. Вызвал функцию-`actions` -> вызвал `git`-комманду -> комманда успешно выполнилась -> обработал `stdout` -> вернул данные
2. Вызвал функцию-`actions` -> вызвал `git`-комманду -> комманда зафейлилась -> пробросил наиболее подходящую ошибку (которая является инстансом [Response](../server/models/responses/response.js)) для это комманды
3. Вызвал функцию-`actions` -> вызвал `git`-комманду которая выполняется 3 секунды -> через 1 секунду вызывается та жа функция-`actions` с теми же аргументами и встает в очередь на ответ -> через 2 секунды обе функции получили свои данные или ошибку.

Тестируется [тут](../test/unit/actions/index.test.js)  

#### 3. Модуль utils
Говоря модуль `utils` я поразумеваю функцию [handleRequest](../server/modules/utils.js),
которая отвечает за валидацию ответа клиенту.

Основные сценарии:
1. получил в аргументах асинхронное действие -> вызвал его -> выполнилось успешно -> обернул в [SuccessResponse](../server/models/responses/success.js) -> отдал клиенту
2. получил в аргументах асинхронное действие -> вызвал его -> зафейлилось c ошибкой, которая является [Response](../server/models/responses/response.js)) -> отдал клиенту
3. получил в аргументах асинхронное действие -> вызвал его -> зафейлилось c ошибкой `JavaScript` -> Обернул в [UnknownFail](../server/models/responses/unknown.js) -> отдал клиенту

Тестируется [тут](../test/unit/utils/handle-request.test.js)